// <auto-generated />
namespace KetoSavageWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateDailyProgressHL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateDailyProgressHL));
        
        string IMigrationMetadata.Id
        {
            get { return "201902132230071_updateDailyProgressHL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
